apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-creator-application-user
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "创作者申请"
    rbac.authorization.halo.run/display-name: "创作者申请"
    rbac.authorization.halo.run/ui-permissions: '["plugin:creator-application:apply"]'
rules:
  - apiGroups: [ "api.creator.jnoasa.cn" ]
    resources: [ "me" ]
    verbs: [ "get" ]
  - apiGroups: [ "api.creator.jnoasa.cn" ]
    resources: [ "applications" ]
    verbs: [ "create" ]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-creator-application-review
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "创作者申请"
    rbac.authorization.halo.run/display-name: "创作者申请审核"
    rbac.authorization.halo.run/ui-permissions: '["plugin:creator-application:review"]'
rules:
  - apiGroups: [ "creator.jnoasa.cn" ]
    resources: [ "creatorapplications" ]
    verbs: [ "get", "list", "update", "patch" ]
  - apiGroups: [ "api.creator.jnoasa.cn" ]
    resources: [ "applications" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "api.creator.jnoasa.cn" ]
    resources: [ "applications/paged" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "api.creator.jnoasa.cn" ]
    resources: [ "applications/review" ]
    verbs: [ "create" ]
